import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  filter: Object[] = [
    {'Sneakers': ['Yeezy',
                'Ultra Boost',
                'NMD',
                'Iniki',
                'Other',
                'One',
                'Two',
                'Three',
                'Four',
                'Five',
                'Six',
                'Seven',
                'Eight',
                'Nine',
                'Ten',
                'Eleven',
                'Twelve',
                'Thirteen',
                'Fourteen',
                'Fifteen',
                'Sixteen',
                'Seventeen',
                'Eighteen',
                'Nineteen',
                'Twenty',
                'Twenty One',
                'Twenty Two',
                'Twenty Three',
                'Twenty Eight',
                'Twenty Nine',
                'Thirty',
                'Thirty One',
                'Packs',
                'Spizike',
                'Other',
                'Foamposite',
                'KD',
                'Kobe',
                'LeBron',
                'Air Force',
                'Air Max',
                'Basketball',
                'SB',
                'Other',
                'Asics',
                'Diadora',
                'Li Ning',
                'Louis Vuitton',
                'New Balance',
                'Puma',
                'Reebok',
                'Saucony',
                'Under Armour',
                'Other']},
    {'Handbags': ['Supreme',
                'Keepall',
                'Speedy',
                'Alma',
                'Neverfull',
                'Noe',
                'Other',
                'Jewelry',
                'Flap',
                'Boy',
                'WOC',
                'Camera',
                'Other',
                'Jewelry',
                'Birkin',
                'Kelly',
                'Constance',
                'Evelyne',
                'Other',
                'Jewelry',
                'Disco',
                'Boston',
                'Jackie',
                'Soho',
                'Other',
                'Jewelry',
                'St. Louis',
                'Anjou',
                'Belvedere',
                'Saigon',
                'Other',
                'Jewelry',
                'Pandora',
                'Nightingale',
                'Antigona',
                'Other']},   
    {'Watches': ['Submariner',
                'Explorer',
                'Daytona',
                'GMT-Master II',
                'Sea-Dweller',
                'Datejust',
                'Day-Date',
                'Yacht-Master',
                'Oyster-Perpetual',
                'Cellini',
                'Sky-Dweller',
                'Other',
                'Royal Oak',
                'Royal Oak Offshore',
                'Other',
                'Speedmaster',
                'Seamaster',
                'Constellation',
                'Other',
                'Tank',
                'Ballon Bleu',
                'Roadster',
                'Santos',
                'Pasha',
                'Other',
                'Calatrava',
                'Nautilus',
                'Aquanaut',
                'Annual Calendar',
                'Perpetual Calendar',
                'Twenty-4',
                'Other',
                'Navitimer',
                'Other',
                'Luminor',
                'Radiomir',
                'Other',
                'Big Pilot',
                'Pilot',
                'Portuguese',
                'Other',
                'Grande Reverso',
                'Master Calendar',
                'Reverso',
                'Other',
                'A. Lange & Sohne',
                'Bell & Ross',
                'Bremont',
                'Chanel',
                'Chopard',
                'Doxa',
                'Ernst Benz',
                'MB&F',
                'Nomos',
                'Oris',
                'Richard Mille',
                'Tag Heuer',
                'Tudor',
                'Urwerk',
                'Vacheron Constantin',
                'Other']},
        {'Collectables': [ ]}
  ];
  object: Object;

  constructor() {
    this.object = Object;
  }

  ngOnInit() {
  }

}
